import {
  Rocket,
  Zap,
  Database,
  Brain,
  Settings2,
  BookOpen,
  Target,
  Workflow,
  Globe,
  FileSpreadsheet,
  Variable,
  Bug,
  Bell,
  Server,
  Film,
  FolderOpen,
  FileText,
  Webhook,
  Smartphone,
  ClipboardCheck,
  Monitor,
  Share2,
  Terminal,
  MessageCircle,
  Mouse,
  Image,
  Wrench,
  BarChart3,
  Eye,
  Network,
  Calculator,
  Clock,
  Puzzle,
} from 'lucide-react'
import type { DocumentItem } from './types'

export const documents: DocumentItem[] = [
  {
    id: 'getting-started',
    title: '🚀 快速入门',
    icon: Rocket,
    description: '5分钟学会使用WebRPA',
  },
  {
    id: 'browser-guide',
    title: '🌐 自动化浏览器',
    icon: Globe,
    description: '浏览器原理与元素选择器',
  },
  {
    id: 'basic-modules',
    title: '⚡ 基础模块详解',
    icon: Zap,
    description: '浏览器操作、表单填写、数据采集等',
  },
  {
    id: 'variables-guide',
    title: '📦 变量系统详解',
    icon: Variable,
    description: '变量类型、引用、列表字典',
  },
  {
    id: 'data-processing',
    title: '📊 数据处理指南',
    icon: Database,
    description: '变量、列表、字典、字符串操作',
  },
  {
    id: 'math-flow-guide',
    title: '🔢 数学统计与CSV',
    icon: Calculator,
    description: '数学运算、统计分析、CSV处理、概率触发器',
  },
  {
    id: 'excel-guide',
    title: '📑 Excel与数据表格',
    icon: FileSpreadsheet,
    description: 'Excel读取与数据采集',
  },
  {
    id: 'database-guide',
    title: '🗄️ 数据库操作',
    icon: Server,
    description: 'MySQL/PostgreSQL/SQLite/Redis 等数据库',
  },
  {
    id: 'network-guide',
    title: '🌐 网络请求与抓包',
    icon: Network,
    description: 'HTTP请求、发送邮件、Webhook、网络抓包',
  },
  {
    id: 'triggers-guide',
    title: '⚡ 触发器使用指南',
    icon: Webhook,
    description: 'Webhook、热键、文件监控、邮件、API触发',
  },
  {
    id: 'scheduled-tasks-guide',
    title: '⏰ 计划任务系统',
    icon: Clock,
    description: '定时执行、重复任务、任务管理',
  },
  {
    id: 'custom-modules-guide',
    title: '🧩 自定义模块',
    icon: Puzzle,
    description: '创建和管理自定义模块，扩展功能',
  },
  {
    id: 'advanced-features',
    title: '🧠 高级功能',
    icon: Brain,
    description: 'AI对话、流程控制、子流程、脚本',
  },
  {
    id: 'ai-vision-guide',
    title: '👁️ AI识别与爬虫',
    icon: Eye,
    description: 'OCR、验证码、人脸识别、AI智能爬虫',
  },
  {
    id: 'desktop-guide',
    title: '🖥️ 桌面应用自动化',
    icon: Monitor,
    description: 'Windows桌面程序控制、窗口管理、控件操作',
  },
  {
    id: 'input-guide',
    title: '🖱️ 屏幕鼠标键盘',
    icon: Mouse,
    description: '屏幕截图、真实鼠标键盘模拟、图像点击',
  },
  {
    id: 'image-guide',
    title: '🖼️ 图像处理',
    icon: Image,
    description: '图像编辑、格式转换、水印、二维码',
  },
  {
    id: 'files-guide',
    title: '📁 文件操作指南',
    icon: FolderOpen,
    description: '文件读写、复制、移动、删除',
  },
  {
    id: 'pdf-guide',
    title: '📄 PDF处理指南',
    icon: FileText,
    description: 'PDF转换、合并、拆分、加密',
  },
  {
    id: 'media-guide',
    title: '🎬 媒体处理指南',
    icon: Film,
    description: '视频压缩、格式转换、音频提取',
  },
  {
    id: 'phone-guide',
    title: '📱 手机自动化指南',
    icon: Smartphone,
    description: 'Android手机控制、点击、输入、截图',
  },
  {
    id: 'bots-guide',
    title: '💬 QQ与微信机器人',
    icon: MessageCircle,
    description: 'QQ消息发送接收、微信自动化',
  },
  {
    id: 'notify-guide',
    title: '📢 多渠道通知',
    icon: Bell,
    description: '钉钉、微信、Telegram、Discord等17种通知',
  },
  {
    id: 'ssh-guide',
    title: '🔐 SSH 远程操作',
    icon: Terminal,
    description: 'SSH连接服务器、执行命令、上传下载文件',
  },
  {
    id: 'sap-guide',
    title: '🏢 SAP自动化',
    icon: Server,
    description: 'SAP GUI自动化、事务码执行、字段操作',
  },
  {
    id: 'feishu-guide',
    title: '🚀 飞书自动化',
    icon: FileSpreadsheet,
    description: '飞书多维表格和电子表格自动化操作',
  },
  {
    id: 'share-guide',
    title: '🔗 网络与屏幕共享',
    icon: Share2,
    description: '局域网文件共享、屏幕实时投屏',
  },
  {
    id: 'utils-guide',
    title: '🛠️ 实用工具',
    icon: Wrench,
    description: '加密哈希、文件对比、颜色转换、打印',
  },
  {
    id: 'test-report-guide',
    title: '📊 测试报告指南',
    icon: ClipboardCheck,
    description: 'Allure测试报告生成与管理',
  },
  {
    id: 'selector-guide',
    title: '🎯 选择器完全指南',
    icon: Target,
    description: 'CSS选择器从入门到精通',
  },
  {
    id: 'notifications-guide',
    title: '🔔 消息通知与交互',
    icon: Bell,
    description: '日志、提示音、音视频播放、用户输入',
  },
  {
    id: 'debug-guide',
    title: '🐛 调试与错误处理',
    icon: Bug,
    description: '调试技巧与性能优化',
  },
  {
    id: 'practical-cases',
    title: '📚 实战案例',
    icon: BookOpen,
    description: '常见场景的完整解决方案',
  },
  {
    id: 'workflow-patterns',
    title: '🔄 工作流模式',
    icon: Workflow,
    description: '常用设计模式和最佳实践',
  },
  {
    id: 'tips-tricks',
    title: '💡 技巧与窍门',
    icon: Settings2,
    description: '让你的工作流更高效',
  },
]
